pydev/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login', views.connexion, name='connexion'),
]

pydev/myapp/urls.py
from django.urls import path
from . import views


app_name = 'myapp'
urlpatterns = [
    path('', views.index, name="index"),
    path('pdf/<int:id>', views.audio, name="pdf"),
    path('del/<int:id>', views.delete, name="remove")
]

pydev/myproject/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("myapp.urls")),
    path('accounts/', include("accounts.urls")),
]

urlpatterns += (
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)+
    static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
)

pydev/accounts/models.py
from django.db import models

# Create your models here.

pydev/myapp/models.py
from django.db import models
from django.contrib import admin
from django.contrib.auth.models import User

# langue
class Langue(models.Model):
    langue = models.CharField(max_length=300)
    code = models.CharField(max_length=300, default='fr')
    create_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.langue)

class LangueAdmin(admin.ModelAdmin):
    list_display = ("langue",)

# PDF
class Pdf(models.Model):
    langue = models.ForeignKey(Langue, on_delete=models.DO_NOTHING)
    pdf = models.FileField(upload_to="pdf")
    status = models.BooleanField(default=False)
    owner = models.ForeignKey(User, on_delete=models.DO_NOTHING)

    def __str__(self):
        return str(self.pdf)

class PdfAdmin(admin.ModelAdmin):
    list_display = ('langue', "pdf", 'status', 'owner')
    
# Audio
class PdfToAudio(models.Model):
    pdf = models.ForeignKey(Pdf, on_delete=models.CASCADE)
    audio = models.FileField(upload_to="audio")
    owner = models.ForeignKey(User, on_delete=models.DO_NOTHING, default=1)
    status = models.BooleanField(default=False)
    create_at = models.DateTimeField(auto_now=True)

class PdfToAudioAdmin(admin.ModelAdmin):
    list_display = ('pdf', "audio", 'status', 'owner', 'create_at')

pydev/myapp/forms.py
from django.forms import ModelForm
from django import forms
from .models import Pdf
class PdfForm(forms.ModelForm):
    class Meta:
        model = Pdf
        fields = ['langue', 'pdf', 'owner'] 

        widgets = {
            'langue': forms.Select(attrs={'class': 'form-control form-select', 'id':'lang-space'}),
            'owner': forms.TextInput(attrs={'class': 'form-control', 'value': '', 'id':'owner', 'type': 'hidden'}),
        }

        labels={'langue' : "Langue du Pdf", "pdf":"Document Pdf"}
        
        pdf = forms.FileField(),

pydev/accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate, login
from django.contrib import messages
from django.contrib.auth.models import User

def connexion(request):
    if request.method=='POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('/')
        else:
            messages.info(request, 'Vos identifiants sont incorrects')
    return render(request, 'accounts/login.html')

pydev/myapp/views.py
from django.shortcuts import render , redirect
import logging
from .forms import PdfForm
from .filehundler import handle_uploaded_file, pdfReader, text_to_audio
from .models import Pdf, PdfToAudio, Langue
from django.contrib.auth.models import User


log = logging.getLogger('log')

def index(request):
    log.error("Message for error")
    pdf_obj = Pdf.objects.filter(owner=request.user.id)
    
    if request.method=="POST": 
        form = PdfForm(request.POST, request.FILES)
        if form.is_valid:
            name, ex = str(request.FILES['pdf']).split('.')
            lang_id = request.POST.get('langue')
            user_id = request.POST.get('owner')
            lang = Langue.objects.get(pk=lang_id)
           
            file_handler = handle_uploaded_file(request.FILES['pdf'], name, ex)
            doc = Pdf()
            doc.pdf = file_handler
            doc.langue = Langue.objects.get(pk=lang_id)
            doc.owner = User.objects.get(pk=user_id)
            doc.save()  
                      
            return redirect(f'/pdf/{doc.id}')
    else:
        form = PdfForm()
    context = {'form':form, 'last_audio':pdf_obj}
    return render(request, 'myapp/index.html', context)



def audio(request, id):
    pdf_obj = Pdf.objects.get(pk=id, owner=request.user)
    audios = PdfToAudio.objects.filter(owner=request.user).order_by('-id')
    file_name_with_extension = pdf_obj.pdf.name.split('/')[1]
    file_name = file_name_with_extension.split('.')[0]
    
    if request.method=='POST':
        lang_code = pdf_obj.langue.code
       
        text = pdfReader(f"media/pdf/{file_name_with_extension}")
        mp = text_to_audio(text, f"media/audio/{file_name}.mp3", lang_code)
        
        audio = PdfToAudio()
        audio.pdf = pdf_obj
        audio.audio = mp
        audio.owner = User.objects.get(id=request.user.id)
        audio.save()
        pdf_obj.status = True
        pdf_obj.save()
        return redirect(f'/pdf/{pdf_obj.id}')
    context = {'file_name': file_name_with_extension, 'pdf_obj':pdf_obj, 'audio':file_name, 'audios':audios}
    return render(request, 'myapp/audio.html', context)


def delete(request, id):
    obj = PdfToAudio.objects.get(id=id)
    obj.delete()
    return redirect('/')

pydev/accounts/templates/accounts/layout/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}
    <title>PDF TO AUDIO</title>
    {% endblock %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <link href="{% static 'css/main.css' %}" rel="stylesheet">
    <link href="{% static 'css/login.css' %}" rel="stylesheet">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-success">
        <div class="container-fluid">
        <a class="navbar-brand" href="/">PyDev</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarScroll">
            <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
                <li class="text-white">{{ request.user.username }}</li>
            </ul>
        </div>
        </div>
    </nav>



    {% block body %} 
        
    {% endblock %}


    
  </body>
  <footer style="color: black; text-align: center; padding: 5.5px" class="footer">Copyright &copy; 2019 - {% now 'Y' %} | PyDev</footer>
</html>

pydev/accounts/templates/accounts/login.html
{% extends 'accounts/layout/base.html' %}

{% block title %}<title>Login</title>  {% endblock %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4">
            <div class="wrapper"> 
                <form class="form-signin" method="POST" action="">  {% csrf_token %}     
                    <h2 class="form-signin-heading">Connexion</h2>
                    {% for message in messages %}
                        <p class="text-danger">{{ message }}</p>
                    {% endfor %}
                    <input type="text" class="form-control" name="username" placeholder="Nom d'utilisateur" required="" autofocus="" />
                    <input type="password" class="form-control" name="password" placeholder="Mot de passe" required=""/>      
                    <button class="btn btn-lg btn-primary btn-block" type="submit">Connexion</button>   
                </form>
            </div> 
        </div>
        <div class="col-md-4"></div>
    </div>
</div>
{% endblock %}

pydev/myapp/templates/myapp/audio.html
{% extends 'myapp/base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PDF TO AUDIO</title>
    <!-- <link href="{% static 'css/main.css' %}" rel="stylesheet"> -->
</head>
<body>
    {% block body %}
    {% if request.user.is_authenticated %}
        <div class="container">
            <div class="col bg-warning mt-5 p-4 text-center text-danger">
                <h1>PDF => AUDIO</h1>
                <a href="/" class="text-black">Charger un pdf</a>
            </div>
        
            <div class="row">
                <div class="col-md-6">
                    {% if pdf_obj.status == True %}
                        <p class="mt-5">{{ file_name }} <span class="text-success">[OK]</span></p>
                    {% else %}
                    <form method="POST" action="" enctype='multipart/form-data' class="mt-5"> {% csrf_token %}
                        {{ file_name }}

                        <button class="btn btn-success btn-text conv" type="submit">
                            Convertir
                            <span class="spinner" id="status-spinner" role="status" aria-hidden="true"></span>
                        </button>
                    </form>
                    {% endif %}

                    <button class="btn btn-danger mt-5 sp-box" type="button" disabled>
                        <span class="patienter" role="status" aria-hidden="true"></span>
                        audio en cours...
                    </button>

                    <audio controls class="mt-5 w-5" id="audio"> 
                        <source src="/media/audio/{{ audio }}.mp3" type="audio/mp3">
                    </audio>
                </div>

                <div class="col-md-6">
                    
                    <h3 class="mt-5">Historique</h3>
                    <p>{{ audios|length }} éléments</p> 
                    {% for audio in audios %}
                        
                        <audio controls class="mt-5 w-5" id="audio">
                            <source src="/{{ audio.audio }}" type="audio/mp3">
                        </audio>
                        <br />
                        <a href='/media/{{ audio.pdf }}'>{{ audio.pdf }}</a> 
                        {{ audio.pdf.langue }} <br />
                        {{ audio.create_at }}
                        {{ audio.pdf.owner }} 
                        <a href="{% url 'myapp:remove' audio.id %}"><img src="{% static 'media/img/delete_icon.png' %}" width="20" height="20" /></a>
                        <hr class="hr"/> 
                        <br /> <br />
                    {% endfor %}
                </div>
            </div>
            
        </div>
    {%  else %}
    <div class="container">
        <div class="col bg-warning mt-5 p-2 text-center text-danger">
            <h5><a href="#">Connectez-vous</a> pour convertir vos document pdf en audio</h5>
        </div>
    </div>
    {% endif %}
    <script src="{%  static 'js/main.js' %}"></script>

    <script>
        let user = '{{request.user.id}}'
        document.querySelector('#owner').value = user
    </script>
    {% endblock %}

</body>
</html>

pydev/myapp/templates/myapp/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}
    <title>PDF TO AUDIO</title>
    {% endblock %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <link href="{% static 'css/main.css' %}" rel="stylesheet">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-success">
        <div class="container-fluid">
        <a class="navbar-brand" href="/">PyDev</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarScroll">
            <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
                <li class="text-white">{{ request.user.username }}</li>
            </ul>
        </div>
        </div>
    </nav>



    {% block body %} 
        
    {% endblock %}


    
  </body>
  <footer style="color: black; text-align: center; padding: 5.5px" class="footer">Copyright &copy; 2019 - {% now 'Y' %} | PyDev</footer>
</html>

pydev/myapp/templates/myapp/index.html
{% extends 'myapp/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Convertisseur</title>
</head>
<body id="home">
    {% block body %}
    <div class="container">
            {% if request.user.is_authenticated %}
                <div class="bg-warning mt-5 p-4 text-center text-danger">
                    <h1>Charger un document</h1>
                    {% if last_audio.last.id %}
                    <a href="/pdf/{{ last_audio.last.id }}" class="text-black">mes audio</a>
                    {% endif %}
                </div>

                <div class="row">
                    <div class="col-md-4">
                        <p class="mt-5 help-texte">écoutez vos pdf en podcast. Plus besoin de lire sur papier. Charger vos pdf, nous les convertirons en audio. séléctionnez la langue de votre pdf et chargez-la.</p>
                    </div>
                    <div class="col-md-4">
                        <form method="POST" action="" enctype='multipart/form-data' class="mt-5"> {% csrf_token %}
                            {{ form|crispy }} <br />
                            <button type="submit" class="btn btn-success charger" id="hidde-con">Charger</button>
                        </form>
                    </div>
                    <div class="col-md-4"></div>
                </div>
            {%  else %}
                <div class="bg-warning mt-5 p-2 text-center text-danger">
                    <h5><a href="{% url 'accounts:connexion' %}">Connectez-vous</a> pour convertir vos document pdf en audio</h5>
                </div>
            {% endif %}
    </div>


    <script>
        let user = '{{request.user.id}}'
        document.querySelector('#owner').value = user
    </script>
    {% endblock %}

</body>
</html>